# Generated by Django 4.2.7 on 2023-11-26 19:04

from django.db import migrations, models
import manager_app.custom_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='book_title')),
                ('author', models.CharField(max_length=200, verbose_name='book_author')),
                ('publish_year', models.IntegerField(validators=[manager_app.custom_validators.publish_year_validator], verbose_name='book_publish_year')),
                ('isbn', models.IntegerField(max_length=13, validators=[manager_app.custom_validators.isbn_validator], verbose_name='book_isbn')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
