# Generated by Django 4.2.7 on 2023-11-26 19:05

from django.db import migrations, models
import manager_app.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.IntegerField(validators=[manager_app.custom_validators.isbn_validator], verbose_name='book_isbn'),
        ),
    ]
