version: '3'

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: ./library_manager/.env
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.0.2-alpine
    container_name: redis_app
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - "6379:6379"
    volumes:
      - ./data/cache:/data

  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: app
    container_name: app_container
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file: ./library_manager/.env
    ports:
      - "8000:8000"
    volumes:
      - ../:/config
    command: bash -c "
      python manage.py migrate
      && python manage.py create_users
      && python manage.py runserver 0.0.0.0:8000
      "

  celery-worker:
    image: app
    container_name: celery-worker
    restart: always
    env_file: ./library_manager/.env
    volumes:
      - ../:/var/www/app/worker
    depends_on:
      redis:
        condition: service_started
      db:
        condition: service_healthy
      app:
        condition: service_started
    command: celery -A config worker -l INFO